export const products = [
  {
    id: 1,
    name: "T-shirt with Tape Details",
    category: "casual",
    gender: "men",
    price: 120,
    oldPrice: null,
    rating: 4.5,
    reviewCount: 120,
    images: ["assets/images/products/tshirt-tape-details-black.jpg"],
    description: "Comfortable cotton t-shirt with modern tape details.",
    tags: ["new-arrival"],
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    category: "casual",
    gender: "men",
    price: 240,
    oldPrice: 260,
    rating: 3.5,
    reviewCount: 98,
    images: ["/assets/images/products/skinny-fit-jeans-blue.jpg"],
    description: "Stretchy skinny jeans for everyday wear.",
    tags: ["new-arrival"],
  },
  {
    id: 3,
    name: "Checkered Shirt",
    category: "casual",
    gender: "men",
    price: 180,
    oldPrice: null,
    rating: 4.5,
    reviewCount: 210,
    images: ["/assets/images/products/checked-shirt-red.jpg"],
    description: "Classic checkered shirt with a relaxed fit.",
    tags: ["new-arrival"],
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    category: "casual",
    gender: "men",
    price: 130,
    oldPrice: 160,
    rating: 4.0,
    reviewCount: 75,
    images: ["/assets/images/products/sleeve-striped-tshirt-orange.jpg"],
    description: "Stylish striped sleeve t-shirt.",
    tags: ["new-arrival"],
  },
  {
    id: 5,
    name: "Vertical Striped Shirt",
    category: "formal",
    gender: "men",
    price: 212,
    oldPrice: 232,
    rating: 4.0,
    reviewCount: 65,
    images: ["/assets/images/products/vertical-striped-shirt.png"],
    description: "Formal vertical striped shirt.",
    tags: ["top-selling"],
  },
  {
    id: 6,
    name: "Courage Graphic T-shirt",
    category: "casual",
    gender: "men",
    price: 145,
    oldPrice: null,
    rating: 4.0,
    reviewCount: 180,
    images: ["/assets/images/products/courage-grahic-T-shirt.png"],
    description: "Bold graphic t-shirt with premium print.",
    tags: ["top-selling"],
  },
  {
    id: 7,
    name: "Loose Fit Bermuda Shorts",
    category: "casual",
    gender: "men",
    price: 80,
    oldPrice: null,
    rating: 3.0,
    reviewCount: 42,
    images: ["/assets/images/products/loose-fit-bermuda-blue.jpg"],
    description: "Lightweight loose fit shorts.",
    tags: ["top-selling"],
  },
  {
    id: 8,
    name: "Faded Skinny Jeans",
    category: "casual",
    gender: "men",
    price: 210,
    oldPrice: null,
    rating: 4.5,
    reviewCount: 140,
    images: ["/assets/images/products/faded-skinny-jeans.png"],
    description: "Trendy faded skinny jeans.",
    tags: ["top-selling"],
  },
  {
    id: 9,
    name: "Gradient Graphic T-shirt",
    category: "casual",
    gender: "men",
    price: 145,
    oldPrice: null,
    rating: 3.5,
    reviewCount: 90,
    images: ["/assets/images/products/gradient-graphic-tshirt.jpg"],
    description: "Gradient print graphic tee.",
    tags: [],
  },
  {
    id: 10,
    name: "Polo with Tipping Details",
    category: "casual",
    gender: "men",
    price: 180,
    oldPrice: null,
    rating: 4.5,
    reviewCount: 110,
    images: ["/assets/images/products/polo-tipping-details.png"],
    description: "Classic polo shirt with tipping collar.",
    tags: [],
  },
  {
    id: 11,
    name: "Polo with Contrast Collar",
    category: "casual",
    gender: "men",
    price: 120,
    oldPrice: null,
    rating: 4.0,
    reviewCount: 60,
    images: ["/assets/images/products/polo-with-contrast-trims.png"],
    description: "Minimal polo with contrast collar.",
    tags: [],
  },
  {
    id: 12,
    name: "Relaxed Fit Jeans",
    category: "casual",
    gender: "men",
    price: 220,
    oldPrice: null,
    rating: 4.2,
    reviewCount: 88,
    images: ["relaxed-1.png"],
    description: "Relaxed fit jeans for daily comfort.",
    tags: [],
  },
  {
    id: 13,
    name: "Basic White Tee",
    category: "casual",
    gender: "women",
    price: 90,
    oldPrice: null,
    rating: 4.6,
    reviewCount: 200,
    images: ["white-tee-1.png"],
    description: "Essential white t-shirt.",
    tags: ["top-selling"],
  },
  {
    id: 14,
    name: "Casual Crop Top",
    category: "casual",
    gender: "women",
    price: 110,
    oldPrice: null,
    rating: 4.3,
    reviewCount: 150,
    images: ["crop-1.png"],
    description: "Modern casual crop top.",
    tags: ["new-arrival"],
  },
  {
    id: 15,
    name: "Denim Jacket",
    category: "casual",
    gender: "women",
    price: 260,
    oldPrice: 300,
    rating: 4.7,
    reviewCount: 95,
    images: ["denim-1.png"],
    description: "Classic denim jacket.",
    tags: ["top-selling"],
  },
  {
    id: 16,
    name: "Oversized Hoodie",
    category: "casual",
    gender: "men",
    price: 200,
    oldPrice: null,
    rating: 4.4,
    reviewCount: 130,
    images: ["hoodie-1.png"],
    description: "Warm oversized hoodie.",
    tags: [],
  },
  {
    id: 17,
    name: "Slim Fit Chinos",
    category: "formal",
    gender: "men",
    price: 230,
    oldPrice: null,
    rating: 4.1,
    reviewCount: 70,
    images: ["chinos-1.png"],
    description: "Smart slim fit chinos.",
    tags: [],
  },
  {
    id: 18,
    name: "Printed Summer Dress",
    category: "casual",
    gender: "women",
    price: 190,
    oldPrice: null,
    rating: 4.8,
    reviewCount: 160,
    images: ["dress-1.png"],
    description: "Light summer dress with print.",
    tags: ["new-arrival"],
  },
  {
    id: 19,
    name: "Formal Blazer",
    category: "formal",
    gender: "women",
    price: 320,
    oldPrice: 360,
    rating: 4.6,
    reviewCount: 55,
    images: ["blazer-1.png"],
    description: "Tailored formal blazer.",
    tags: [],
  },
  {
    id: 20,
    name: "Everyday Joggers",
    category: "casual",
    gender: "men",
    price: 150,
    oldPrice: null,
    rating: 4.2,
    reviewCount: 100,
    images: ["joggers-1.png"],
    description: "Comfort joggers for daily wear.",
    tags: [],
  },
];
